### ISSUE TITLE
Feature Request: Svelte-Supabase hackathon boilerplate

### ISSUE THREAD

**Issue by j2l** [joshnuss/1000experiments.dev#6]
Hello,
I wonder if Svelte can lead the challenge of https://github.com/topics/hackathon
There are some trials at https://github.com/search?q=svelte+hackathon but most boilerplates are already not working.

What do you think?

Have a great day of experiments!

**Comment by joshnuss** [comment]
Hi @j2l!

When you say "most boilerplates are not working", is there something specific about templates for hackathons?
Couldn't you use any?

Not sure I understood, can you clarify?

**Comment by j2l** [comment]
Hi @joshnuss ,

Sure! Because sapper is end of life, replaced by Svelte Kit, the svelte hackathon boilerplates made a few months ago are broken and/or not usable in a few weeks/months from now, like: https://github.com/mylastore/svelte-boilerplate

Meanwhile hackathon boilerplates are increasingly good (react, vue, ...), check the reference at https://hackathon-starter.walcony.com/ (https://github.com/sahat/hackathon-starter).

Svelte Kit hackathon boilerplate would be fantastic for hackathon and Svelte would gain popularity among coders.

Disclaimer: I say that also because I participate in an European hackathon at the end of this month and when I tried all svelte boilerplates to prepare for it, I ended with nothing and I wrote this post because you're a wiz with Svelte :smile:

**Comment by joshnuss** [comment]
oh I see what you mean now,

Do you want to try migrating the sapper boilerplate project to svelte-kit? There is a helpful guide here: https://kit.svelte.dev/migrating

I'd be happy to assist, maybe I can review some PRs?

Just add me as a reviewer on PRs, or if you have more questions, my username is joshnuss on Discord.

**Comment by j2l** [comment]
Hello Joshua,
Thank you! I'll try that and let you know. I'll add you as reviewer.
I have new business meetings so sometimes days are off screen.
